### ISSUE TITLE
how to generate pssm, hmm, and dssp features?

### ISSUE THREAD

**Issue by onlyonewater** [yuanqm55/GraphPPIS#1]
hi, authors, after reading your paper, I have a problem about how to generate pssm, hmm, and dssp features, could you release the part of these code? or could you tell me use what tools to generate them?

thanks!!!

**Comment by yuanqm55** [comment]
Hi! Thanks for your interest in our paper! What you need can be found in this new GitHub repository: https://github.com/biomed-AI/GraphPPIS. The "Software and database requirement" section in README describes the tools and databases used to generate PSSM, HMM and DSSP. No. 246, 247 and 181 lines in "GraphPPIS_predict.py" describe the commands you should run.

**Comment by yuanqm55** [comment]
> hi, authors, after reading your paper, I have a problem about how to generate pssm, hmm, and dssp features, could you release the part of these code? or could you tell me use what tools to generate them?
> 
> thanks!!!

Hi! Thanks for your interest in our paper! What you need can be found in this new GitHub repository: https://github.com/biomed-AI/GraphPPIS. The "Software and database requirement" section in README describes the tools and databases used to generate PSSM, HMM and DSSP. No. 246, 247 and 181 lines in "GraphPPIS_predict.py" describe the commands you should run.
